### PR TITLE
get credential using findCredentialById, passing context

### PR DESCRIPTION
**Pull request by LeoQuote**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

like https://github.com/jenkinsci/github-branch-source-plugin/pull/527 , this pr use `findCredentialById` to get credential, and the build context is also passed, make it possible to use the plugin without organization name.

### CODE REVIEW

**Comment by LeoQuote** [comment]
seems to be an error

```
java.lang.ClassCastException: class hudson.scm.NullSCM cannot be cast to class hudson.plugins.git.GitSCM (hudson.scm.NullSCM is in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @6fdbe764; hudson.plugins.git.GitSCM is in unnamed module of loader jenkins.util.URLClassLoader2 @a76e90f)
        at io.jenkins.plugins.checks.github.SCMFacade.findGitHubAppCredentials(SCMFacade.java:132)
        at io.jenkins.plugins.checks.github.GitHubChecksContext.findGitHubAppCredentials(GitHubChecksContext.java:114)
        at io.jenkins.plugins.checks.github.GitHubChecksContext.hasGitHubAppCredentials(GitHubChecksContext.java:89)
        at io.jenkins.plugins.checks.github.GitHubChecksContext.hasValidCredentials(GitHubChecksContext.java:103)
        at io.jenkins.plugins.checks.github.GitHubSCMSourceChecksContext.isValid(GitHubSCMSourceChecksContext.java:79)
        at io.jenkins.plugins.checks.github.GitHubChecksPublisherFactory.createPublisher(GitHubChecksPublisherFactory.java:64)
        at io.jenkins.plugins.checks.github.GitHubChecksPublisherFactory.createPublisher(GitHubChecksPublisherFactory.java:47)
        at io.jenkins.plugins.checks.api.ChecksPublisherFactory.lambda$fromRun$0(ChecksPublisherFactory.java:89)
```

**Comment by LeoQuote** [comment]
The error above has been fixed

**Comment by LeoQuote** [comment]
```
java.lang.ClassCastException: class hudson.scm.NullSCM cannot be cast to class hudson.plugins.git.GitSCM (hudson.scm.NullSCM is in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @61bcd567; hudson.plugins.git.GitSCM is in unnamed module of loader jenkins.util.URLClassLoader2 @1d00af3e)
	at io.jenkins.plugins.checks.github.SCMFacade.findGitHubAppCredentials(SCMFacade.java:132)
	at io.jenkins.plugins.checks.github.GitHubChecksContext.findGitHubAppCredentials(GitHubChecksContext.java:114)
	at io.jenkins.plugins.checks.github.GitHubChecksContext.hasGitHubAppCredentials(GitHubChecksContext.java:89)
	at io.jenkins.plugins.checks.github.GitHubChecksContext.hasValidCredentials(GitHubChecksContext.java:103)
	at io.jenkins.plugins.checks.github.GitHubSCMSourceChecksContext.isValid(GitHubSCMSourceChecksContext.java:79)
	at io.jenkins.plugins.checks.github.GitHubChecksPublisherFactory.createPublisher(GitHubChecksPublisherFactory.java:64)
	at io.jenkins.plugins.checks.github.GitHubChecksPublisherFactory.createPublisher(GitHubChecksPublisherFactory.java:47)
	at io.jenkins.plugins.checks.api.ChecksPublisherFactory.lambda$fromRun$0(ChecksPublisherFactory.java:89)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at io.jenkins.plugins.checks.api.ChecksPublisherFactory.fromRun(ChecksPublisherFactory.java:92)
	at io.jenkins.plugins.checks.api.ChecksPublisherFactory.fromRun(ChecksPublisherFactory.java:69)
	at io.jenkins.plugins.analysis.core.steps.WarningChecksPublisher.publishChecks(WarningChecksPublisher.java:81)
	at io.jenkins.plugins.analysis.core.steps.IssuesRecorder.publishResult(IssuesRecorder.java:865)
	at io.jenkins.plugins.analysis.core.steps.IssuesRecorder.record(IssuesRecorder.java:781)
	at io.jenkins.plugins.analysis.core.steps.IssuesRecorder.perform(IssuesRecorder.java:743)
	at io.jenkins.plugins.analysis.core.steps.RecordIssuesStep$Execution.run(RecordIssuesStep.java:1159)
	at io.jenkins.plugins.analysis.core.steps.RecordIssuesStep$Execution.run(RecordIssuesStep.java:1115)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

hmmm strange, the error still appears occasionally ...

**Comment by LeoQuote** [comment]
I’m not capable to fix all the issues , closing 🥹

**Comment by jglick** [comment]
@LeoQuote can you at least file something in https://github.com/jenkinsci/github-checks-plugin/issues/new/choose describing what bug or RFE you consider this to be solving, in case someone else wants to try?

**Pull request closed without merging**
