### PR TITLE
Fix re-run from forks

### PR DESCRIPTION
**Pull request by timja**
Fixes https://github.com/jenkinsci/github-checks-plugin/issues/56

### CODE REVIEW

**Comment by timja** [comment]
FYI @jglick

**Review by oleg-nenashev — APPROVED** [review]
relying on externalId seems to be the best way to go. the implementation should work in the majority of cases, but I am not sure about Organization/Folders scans in Computed Folders. I can imagine a case when the rerun arrives in the middle of branch recreation for aggressive cleanup strategies. regardless of whether it is a real concern or not, the change is a net improvement

**Review by XiongKezhi — CHANGES_REQUESTED** [review]
Tested on my local machine and worked.

Just some minor warnings from PMD and checkstyle left.

**Comment by timja** [comment]
grr why didn't it fail locally, I ran `mvn clean install` -.-

**Review by XiongKezhi — APPROVED** [review]

**Pull request merged**
